---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.1.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
import numpy as np
import matplotlib.pyplot as plt
import scipy                  # http://scipy.org/
from scipy import signal

from IPython.display import Image  
# %matplotlib inline
params = {'legend.fontsize': 12,
          'figure.figsize': (10, 10),
         'axes.labelsize': 12,
         'axes.titlesize': 12,
         'xtick.labelsize':12,
         'ytick.labelsize':12}
plt.rcParams.update(params) 


plt.rcParams.update(params)
from IPython.display import Image





```

<!-- #region -->
## Divisor capacitivo:

Los datos son $C'$, $R''$ y $R$.

Buscamos los valores de $C_1$ y $C_2$.

Empezando desde el paralelo de $R$ y $C_1$, donde para tener el modelo serie ($R'$ y $C_1'$) podemos escribir  
$Q_{m1}$ como:

$$ Q_{m1} = R \omega C_1  = \frac{1}{R'  \omega C_1' }$$ 

Entonces:
$$ R' = \frac{R}{(1+Q_{m1}^2)}$$ 
$$ X_1' = \frac{X_1}{(1+\frac{1}{Q_{m1}^2})}$$ 
$$ C_1' = C_1(1+\frac{1}{Q_{m1}^2})$$


Al modelo serie de $R'$ y $C_1'$ hay que agregar $C_2$ ($C_2$ en serie con $C_1'$) :
$$ C = \frac{C_2C_1'}{C_2+C_1'}$$

Despejando $C_2$:
$$ C_2 = \frac{C_1' C}{C_1' - C}$$


Ahora tenemos como resultado la serie de $C$ con $R'$. 

Para tener el modelo serie del paralelo de $R''$ con $C'$, calculamos $Q_{m2}$.

$$ Q_{m2} = R'' \omega C'  $$

$$ R''  = R'(1+Q_{m2}^2) $$
$$ C'     = C (1+\frac{1}{Q_{m2}^2})$$
$$ C     = \frac{C'}{ (1+\frac{1}{Q_{m2}^2})}$$


Recordando: 
$$ R' = \frac{R}{(1+Q_{m1}^2)}$$ 


Remplanzando R' 
$$ R''  = R  \frac{(1+Q_{m2}^2) }{(1+Q_{m1}^2)} $$

Dado que $Q_{m1}$ es incognita, despejamos:

$$ (1+Q_{m1}^2) = \frac{R}{R''}(1+Q_{m2}^2)$$

$$ Q_{m1} = \sqrt[]{\frac{R}{R''}(1+Q_{m2}^2)-1}$$

Conocido $Q_{m1}$, podemos calcular $C_1$:
$$ C_2 = \frac{Q_{m1}}{R \omega} $$ 

Para calcular $C_2$, calculamos $C_1'$ y $C$: 
$$ C_1' = C_1(1+\frac{1}{Q_{m1}^2})$$
$$ C     = \frac{C'}{ (1+\frac{1}{Q_{m2}^2})}$$

Entonces:
$$ C_2 = \frac{C_1' C}{C_1' - C}$$


## Por lo tanto:

Los datos son $C'$, $R''$ y $R$.

Buscamos los valores de $C_2$ y $C_1$.

$$ Q_{m2} = R'' \omega C'  $$

$$ Q_{m1} = \sqrt[]{\frac{R}{R''}(1+Q_{m2}^2)-1}$$

$$ C_1 = \frac{Q_{m1}}{R \omega} $$ 

$$ C_1' = C_1(1+\frac{1}{Q_{m1}^2})$$

$$ C     = \frac{C'}{ (1+\frac{1}{Q_{m2}^2})}$$

$$ C_2 = \frac{C_1' C}{C_1' - C}$$



<!-- #endregion -->

```{python}

fo  = 120e6
wo = 2*np.pi*fo

# Datos
Csmin = 10e-12 
rpp = 1500
r   = 150
Qo = 200
Qc = 80
L  = ((1/Qc-1/Qo)/wo)*rpp
print(L/1e-9)

Cp = 1/(L*wo**2)
print(Cp/1e-12)



Qm2 = rpp*wo*(Cp-Csmin)
Qm1 = ((r/rpp)*(1+Qm2**2)-1)**(1/2)

print(Qm2,Qm1)

C1  = Qm1/(r*wo)

C1p = C1*(1+1/(Qm1**2))
  
C   = (Cp-Csmin)*(1+1/(Qm2**2))

C2  = 1 /(1/C-1/C1p)


print(C1/1e-12, C2/1e-12)
```

```{python}

print('Los datos empleados para los calculos:')
print('.param RL  =  {:1.1f} '.format(rpp) )
print('.param C1 =  {:1.3e} '.format(C1) )
print('.param C2 =  {:1.3e} '.format(C2) )


print('.param L  =  {:1.4e} '.format(L) )
print('.param rg  =  {:1.2f} '.format(r) )


```

```{python}
fo  = 120e6
wo = 2*np.pi*fo


Cs = 1/(L*wo**2)
print(Cs/1e-12)




```

<!-- #region -->
### Analizando.

A partir de :

$$ Q_{m1} = \sqrt[]{\frac{R_L}{R_L''}(1+Q_{m2}^2)-1}$$

Podemos llamar $N^2 =\frac{R_L''}{R_L}$, donde $N$ será mayor a 1 ya que  $R_L'' > R_L$.

$$ Q_{m1} = \sqrt[]{\frac{(1+Q_{m2}^2)}{N^2}-1}$$

Si ahora $ Q_{m2} > 10$, entonces: 

$$ Q_{m1} = \sqrt[]{\frac{(Q_{m2}^2)}{N^2}-1}$$

Donde si $ Q_{m1} > 10$, podemos escribir:

$$ Q_{m1} \sim \frac{Q_{m2}}{N}$$



# Procedimiento de cálculo si $Q_{m2} > 10$ 

$$ Q_{m2} = R_L'' \omega C'  $$

$$ N =\sqrt[]{\frac{R_L''}{R_L}} $$

$$ Q_{m1} \sim \frac{Q_{m2}}{N}$$

## Si $Q_{m1} < 10$ entonces: 

Volvemos a calcular $Q_{m1}$: 

$$ Q_{m1} = \sqrt[]{\frac{(1+Q_{m2}^2)}{N^2}-1}$$

$$ C_2 = \frac{Q_{m1}}{R_L \omega} $$ 

$$ C_2' = C_2(1+\frac{1}{Q_{m1}^2})$$

$$ C     = \frac{C'}{ (1+\frac{1}{Q_{m2}^2})}$$

$$ C_1 = \frac{C_2' C}{C_2' - C}$$


## Si $Q_{m1} > 10$ entonces: 


$$ C_2 = \frac{Q_{m1}}{R_L \omega} $$ 

Siendo $Q_{m1}$:

$$ Q_{m1} \sim \frac{Q_{m2}}{N}$$

$$ C_2 \sim \frac{Q_{m2}}{N R_L \omega} $$ 

$$ C_2 \sim \frac{R_L'' \omega C'}{N R_L \omega} $$ 

$$ C_2 \sim \frac{N^2 \omega C'}{N \omega} $$ 

$$ C_2 \sim N C' $$ 

Y para calcular $C_1$:

$$ C_1 = \frac{C_2' C'}{C_2' - C'}$$

$$ C_2' \sim C_2 $$ 

$$ C_1 = \frac{C_2 C'}{C_2 - C'}$$

$$ C_1 = \frac{N C' }{N  - 1}$$

<!-- #endregion -->
